Drop schema if exists  `Final_Project`;
CREATE schema `Final_Project`;
USE `Final_Project`;
SET AUTOCOMMIT=0;

DROP TABLE IF EXISTS `Users`;
CREATE TABLE `Users`(
`User_ID` INT(6) NOT NULL AUTO_INCREMENT,
`First_Name` VARCHAR(30),
`Last_Name` VARCHAR(30),
`birthday` DATE,
`email`TEXT(30),
`password` VARCHAR(30),
PRIMARY KEY(`User_ID`)
)ENGINE=InnoDB AUTO_INCREMENT=16;

DROP TABLE IF EXISTS `Business_User`;
CREATE TABLE `Business_User`(
`Position_x` FLOAT(6) NOT NULL,
`Position_y` FLOAT(6) NOT NULL,
`coupon` VARCHAR(50),
`User_ID` INT(6) NOT NULL ,
`Business_ID` INT(6) NOT NULL ,
PRIMARY KEY(Business_ID)
FOREIGN KEY (User_ID) REFERENCES Users(User_ID) ON DELETE CASCADE ON UPDATE CASCADE
)ENGINE=InnoDB AUTO_INCREMENT=16;

DROP TABLE IF EXISTS `Advertiser_User`;
CREATE TABLE `Advertiser_User`(
`Company` VARCHAR(30),
`Type_of_business` VARCHAR(30),
`Business description` VARCHAR(30),
`User_ID` INT(6) NOT NULL,
`Advertiser_ID` INT(6) NOT NULL AUTO_INCREMENT,
PRIMARY KEY(Advertiser_ID),
FOREIGN KEY (User_ID) REFERENCES Users(User_ID) ON DELETE CASCADE ON UPDATE CASCADE
)ENGINE=InnoDB AUTO_INCREMENT=16;

DROP TABLE IF EXISTS `Coupon`;
CREATE TABLE `Coupon`(
`Coupon_ID` INT(6) NOT NULL AUTO_INCREMENT,
`Coupon_name` VARCHAR(30),
`Owner` VARCHAR(30),
`Publisher`FLOAT(6) NOT NULL,
`StratDate` DATE,
`EndDate` DATE,
`Coupon_link` VARCHAR(30),
PRIMARY KEY(Coupon_ID)
)ENGINE=InnoDB AUTO_INCREMENT=16;


DROP TABLE IF EXISTS `Ad`;
CREATE TABLE `Ad` (
`index_ad` INT(6) NOT NULL AUTO_INCREMENT,
`User_ID`INT(6) NOT NULL,
`Ad_ID` INT(6) NOT NULL,
 PRIMARY KEY(index_ad)
 FOREIGN KEY (User_ID) REFERENCES Advertiser_User(User_ID) ON DELETE CASCADE ON UPDATE CASCADE
)ENGINE=InnoDB AUTO_INCREMENT=16;

DROP TABLE IF EXISTS `Business_ap`;
CREATE TABLE `Business_ap`(
  `ap_Business_index` INT(6) NOT NULL AUTO_INCREMENT,
  `User_ID` INT(6) NOT NULL,
  `wifi_index` INT(6) NOT NULL ,
  PRIMARY KEY(ap_Business_index)
FOREIGN KEY (User_ID) REFERENCES Business_User(User_ID) ON DELETE CASCADE ON UPDATE CASCADE
)ENGINE=InnoDB AUTO_INCREMENT=16;

DROP TABLE IF EXISTS `wifi`;
CREATE TABLE `wifi`(
  `wifi_index` INT(6) NOT NULL AUTO_INCREMENT,
  `wifi_Position_x` FLOAT(6) NOT NULL,
  `wifi_Position_y` FLOAT(6) NOT NULL,
  PRIMARY KEY(wifi_index)
)ENGINE=InnoDB AUTO_INCREMENT=16;

DROP TABLE IF EXISTS `Business_Relationship`;
CREATE TABLE `Business_Relationship`(
  `index_bus` INT(6) NOT NULL AUTO_INCREMENT,
  `User_ID` INT(6) NOT NULL ,
  `Coupon_ID` INT(6) NOT NULL ,
  `Business_ID` INT(6) NOT NULL,
  PRIMARY KEY(index_bus),
  FOREIGN KEY (Coupon_ID)  REFERENCES Coupon(Coupon_ID) ON DELETE CASCADE ON UPDATE CASCADE
)ENGINE=InnoDB AUTO_INCREMENT=16;
